local map = vim.keymap.set

-- moving lines up and down (Alt+j/k)
map('n', '<A-j>', ':m .+1<CR>==')
map('n', '<A-k>', ':m .-2<CR>==')
map('i', '<A-j>', '<Esc>:m .+1<CR>==gi')
map('i', '<A-k>', '<Esc>:m .-2<CR>==gi')
map('v', '<A-j>', ":m '>+1<CR>gv=gv")
map('v', '<A-k>', ":m '<-2<CR>gv=gv")

-- hop
map('n', '<Space><CR>', '<cmd>HopWord<CR>')
map('v', '<Space><CR>', '<cmd>HopWord<CR>')
map('n', ',w', '<cmd>HopWord<CR>')
map('v', ',w', '<cmd>HopWord<CR>')
map('n', ',l', '<cmd>HopLine<CR>')
map('v', ',l', '<cmd>HopLine<CR>')
map('n', ',a', '<cmd>HopAnywhere<CR>')
map('v', ',a', '<cmd>HopAnywhere<CR>')
map('n', ',c', '<cmd>HopAnywhereCurrentLine<CR>')
map('v', ',c', '<cmd>HopAnywhereCurrentLine<CR>')
map('n', ',/', '<cmd>HopPattern<CR>')
map('v', ',/', '<cmd>HopPattern<CR>')
map('n', ',f', '<cmd>HopChar1<CR>')
map('v', ',f', '<cmd>HopChar1<CR>')

-- place this in one of your configuration file(s)
map('', 'f', "<cmd>lua require'hop'.hint_char1({ direction = require'hop.hint'.HintDirection.AFTER_CURSOR, current_line_only = true })<cr>", {})
map('', 'F', "<cmd>lua require'hop'.hint_char1({ direction = require'hop.hint'.HintDirection.BEFORE_CURSOR, current_line_only = true })<cr>", {})
map('', 't', "<cmd>lua require'hop'.hint_char1({ direction = require'hop.hint'.HintDirection.AFTER_CURSOR, current_line_only = true, hint_offset = -1 })<cr>", {})
map('', 'T', "<cmd>lua require'hop'.hint_char1({ direction = require'hop.hint'.HintDirection.BEFORE_CURSOR, current_line_only = true, hint_offset = 1 })<cr>", {})
